name: MCEngineIdentity
main: io.github.mcengine.papermc.identity.engine.MCEngineIdentityPaperMC
version: 1.0.0
api-version: '1.20'
author: MCEngine
commands:
  identity:
    description: Identity management and inventory save/load demo
    usage: /identity
    permission: mcengine.identity.use
permissions:
  mcengine.identity.use:
    default: true
